Menu:
  Home: Home
  Archives: Archives
  Tags: Tags

Paginator:
  Prev: Prev
  Next: Next

userInfo:
  logo: img/vn.jpg
  name: ijinxin
  motto: When you see worthy ones, strive to equal them
  location: SZ China
  email: 874450097@qq.com

Post:
  visit: visited

copyright:
  author: Author
  link: Link
  license: License
